---
abstract: 'Plack Application to provide AJAX to MQTT bridge'
author:
  - 'Mark Hindess <soft-cpan@temporalanomaly.com>'
build_requires:
  English: 0
  HTTP::Request::Common: 0
  Net::MQTT::Constants: 0
  Net::MQTT::Message: 0
  Plack::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-App-MQTT
requires:
  AnyEvent: 0
  AnyEvent::MQTT: 1.112320
  JSON: 0
  MIME::Base64: 0
  Plack::Component: 0
  Plack::Request: 0
  Plack::Util::Accessor: 0
  Scalar::Util: 0
  Sub::Name: 0
  Text::MicroTemplate: 0
  Try::Tiny: 0
  constant: 0
  parent: 0
resources:
  bugtracker: https://github.com/beanz/plack-app-mqtt-perl/issues
  repository: git://github.com/beanz/plack-app-mqtt-perl.git
version: 1.112340
